#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h

. /tmp/ci/function

install_apt

check_build_type
case "$build_type" in
		 V)
		 tg "*$rom_name Build Triggered!*
*Build Type:* \`$build_type\`
*Device:* \`$device_codename\`
*Cirrus Task:* [Here]($progress)"
		 ;; # else
		 *)
		 tg "*$rom_name Triggered New Build*
*Reason:* \`$rom_name is not compiled yet..!\`
*Build Type:* \`$build_type\`
*Cirrus Task:* [Here]($progress)"
esac

cd /tmp # Where to download cccahe

echo "• Downloading CCACHE •"
down https://worst-generation.prajwals.workers.dev/4:/$device_codename/$rom_name/ccache.tar.gz || down https://worst-generation.prajwals.workers.dev/4:/$device_codename/$rom_name/ccache.tar.gz
if [ -e *.tar.gz ]; then
tg "*$rom_name Ccache Downloaded Successfully!*
*Size:* \`$(ls -sh ${PWD}/ccache.tar.gz | cut -d - -f 1 | cut -d / -f 1)\`
*Download Time:* \`$(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).\`
*Cirrus Task:* [Here]($progress)"
else
tg "`Skipping CCACHE Download on 1st build..!`"
fi

# Extract ccache so ci can use it
echo "• Extracting CCACHE •"
if [ -e *.tar.gz ]; then
time tar xf *.tar.gz
fi

# Remove unnecessary downloaded file
rm -rf *.tar.gz

# fix
echo "" > /etc/mtab

# Start new build if system img compiled
case "$build_type" in
		 S|s)
		 echo "• Build Type is System | Started loop•"
		 sleep 70m # start loop after 70mins
		 ;; # else
		 *) # skip the script
		 echo "• Build Type is not System | Skipped Script •"
		 exit 1
esac
while true; do
if [ -e /tmp/rom/out/target/product/$device_codename/system.img ]; then
echo "R" > /tmp/build_type.txt
tg "*System Compilation completed!*
\`Starting Cache upload..\`
*Cirrus Task:* [Here]($progress)"
bash /tmp/ci/upload_ccache
else
sleep 2m
fi
done&
