#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/Project-Elixir/official_manifest -b snow -g default,-mips,-darwin,-notdefault
git clone https://github.com/$ghost/local_manifest_vince.git --depth 1 -b elixir-12 .repo/local_manifests

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

tg "*$rom_name Source Sync Completed!*
*Size:* \`$(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)\`
*Sync Time:* \`$(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).\`
*Cirrus Task:* [Here]($progress)"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
